# Generated by Django 5.0.4 on 2024-05-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_password_registration_password1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=15, verbose_name='Пароль')),
            ],
        ),
    ]
